In [3]:
import numpy as np 
import matplotlib.pyplot as plt 

arr = np.random.rand(224,352) 
print(arr)

[[0.63943514 0.10291524 0.96788966 ... 0.67200592 0.58085688 0.64712467]
 [0.67568915 0.16798848 0.65307793 ... 0.11649615 0.34698509 0.13239482]
 [0.99070406 0.47584992 0.57818145 ... 0.13229917 0.56497727 0.56736184]
 ...
 [0.33380357 0.68737791 0.968026   ... 0.23774181 0.91104144 0.42445625]
 [0.32518344 0.3072775  0.33225212 ... 0.71121041 0.75662323 0.06662833]
 [0.93243576 0.19961922 0.78909269 ... 0.96865751 0.82679749 0.5474396 ]]
